/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class ImagesRes {
  ImagesRes._();

  static const String PLUGIN_NAME = 'proflutter1';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String LOGOUT = 'images/Logout.png';
  static const String SORRY = 'images/Sorry.PNG';
  static const String SPLASH_ZOOM = 'images/Splash_zoom.png';
  static const String SPLASH = 'images/splash.png';
}
